CREATE TABLE `Adres` (
	`ADRES_ID` INT NOT NULL AUTO_INCREMENT,
	`MIASTO_ID` varchar(3) NOT NULL,
	`ULICA` varchar(255) NOT NULL,
	`NR_BUDYNKU` varchar(5) NOT NULL,
	`KOD_POCZTOWY` varchar(6) NOT NULL,
	PRIMARY KEY (`ADRES_ID`)
);

CREATE TABLE `Miasto` (
	`MIASTO_ID` varchar(3) NOT NULL,
	`MIASTO` varchar(255) NOT NULL,
	PRIMARY KEY (`MIASTO_ID`)
);

CREATE TABLE `Student` (
	`NR_INDEKSU` varchar(15) NOT NULL,
	`IMIE` varchar(20) DEFAULT 'NULL',
	`NAZWISKO` varchar(20) NOT NULL,
	`DATA_ROZPOCZECIA_STUDIOW` DATE NOT NULL,
	`DATA_ZAKONCZENIA_STUDIOW` DATE,
	`MIEJSCE_URODZENIA_ID` varchar(3),
	`ADRES_EMAIL` varchar(25) NOT NULL,
	`NUMER_TELEFONU` varchar(15) DEFAULT 'NULL',
	`POMOC_MATERIALNA_ID` varchar(3) NOT NULL,
	PRIMARY KEY (`NR_INDEKSU`)
);

CREATE TABLE `Kierunek` (
	`KIERUNEK_ID` varchar(10) NOT NULL,
	`NAZWA_KIERUNKU` varchar(255) NOT NULL,
	`WYDZIAL_ID` varchar(10) NOT NULL,
	PRIMARY KEY (`KIERUNEK_ID`)
);

CREATE TABLE `Pracownik` (
	`PRACOWNIK_ID` INT NOT NULL AUTO_INCREMENT,
	`IMIE` varchar(20) DEFAULT 'NULL',
	`NAZWISKO` varchar(20) NOT NULL,
	`TYTUL_NAUKOWY` varchar(20) NOT NULL,
	`ADRES_EMAIL` varchar(20) NOT NULL,
	PRIMARY KEY (`PRACOWNIK_ID`)
);

CREATE TABLE `Zajecia` (
	`PRACOWNIK_ID` INT NOT NULL,
	`PRZEDMIOT_ID` INT NOT NULL
);

CREATE TABLE `Przedmiot` (
	`PRZEDMIOT_ID` INT NOT NULL,
	`PRZEDMIOT_NAZWA` varchar(255) NOT NULL,
	`GRUPA_ID` INT NOT NULL,
	`SEMESTR_ID` INT NOT NULL,
	`KIERUNEK_ID` varchar(10) NOT NULL,
	PRIMARY KEY (`PRZEDMIOT_ID`)
);

CREATE TABLE `Ocena` (
	`NR_INDEKSU` varchar(15) NOT NULL,
	`PRZEDMIOT_ID` INT NOT NULL,
	`OCENA` DECIMAL(2,1)
);

CREATE TABLE `Wydzial` (
	`WYDZIAL_ID` varchar(10) NOT NULL,
	`WYDZIAL_NAZWA` varchar(255) NOT NULL,
	`ADRES_ID` INT NOT NULL,
	PRIMARY KEY (`WYDZIAL_ID`)
);

CREATE TABLE `Praca_dyplomowa` (
	`PRACA_DYPLOMOWA_ID` INT NOT NULL AUTO_INCREMENT,
	`TYP_PRACY_DYPLOMOWEJ_ID` INT NOT NULL,
	`PRACA_DYPLOMOWA_TYTUL` varchar(255) NOT NULL,
	`OCENA_ZA_PRACE` DECIMAL(2,1) NOT NULL,
	`OCENA_ZA_OBRONE` DECIMAL(2,1) NOT NULL,
	`DATA_OBRONY` DATE NOT NULL,
	`RECENZENT_ID` INT NOT NULL,
	PRIMARY KEY (`PRACA_DYPLOMOWA_ID`)
);

CREATE TABLE `Grupa` (
	`GRUPA_ID` INT NOT NULL AUTO_INCREMENT,
	`GRUPA_NUMER` varchar(2) NOT NULL,
	PRIMARY KEY (`GRUPA_ID`)
);

CREATE TABLE `student_platnosci` (
	`NR_INDEKSU` varchar(15) DEFAULT 'NULL',
	`PLATNOSCI_ID` INT
);

CREATE TABLE `Platnosci` (
	`PLATNOSCI_ID` INT NOT NULL AUTO_INCREMENT,
	`TYTUL_WPLATY` varchar(255) NOT NULL,
	`WYSOKOSC_OPLATY` DECIMAL(6,2) NOT NULL,
	`DATA_WPLATY` DATE NOT NULL,
	PRIMARY KEY (`PLATNOSCI_ID`)
);

CREATE TABLE `System_pomocy_studentom` (
	`POMOC_ID` varchar(3) NOT NULL,
	`ZAPOMOGA` DECIMAL(6,2),
	`MIEJSCE_W_AKADEMIKU_ID` INT,
	`STYPENDIUM_ID` INT,
	PRIMARY KEY (`POMOC_ID`)
);

CREATE TABLE `Miejsce_w_akademiku` (
	`MIEJSCE_W_AKADEMIKU_ID` INT NOT NULL AUTO_INCREMENT,
	`AKADEMIK_ID` INT NOT NULL,
	`NUMER_POKOJU_ID` INT NOT NULL,
	PRIMARY KEY (`MIEJSCE_W_AKADEMIKU_ID`)
);

CREATE TABLE `Akademik` (
	`AKADEMIK_ID` INT NOT NULL AUTO_INCREMENT,
	`NUMER_AKADEMIKA` DECIMAL(2,0) NOT NULL,
	`ADRES_ID` INT NOT NULL,
	PRIMARY KEY (`AKADEMIK_ID`)
);

CREATE TABLE `Numer_pokoju` (
	`NUMER_POKOJU_ID` INT NOT NULL AUTO_INCREMENT,
	`NUMER_POKOJU` varchar(5) NOT NULL,
	PRIMARY KEY (`NUMER_POKOJU_ID`)
);

CREATE TABLE `Semestr` (
	`SEMESTR_ID` INT NOT NULL AUTO_INCREMENT,
	`SEMESTR` INT NOT NULL,
	PRIMARY KEY (`SEMESTR_ID`)
);

CREATE TABLE `Typ_pracy_dyplomowej` (
	`TYP_PRACY_DYPLOMOWEJ_ID` INT NOT NULL AUTO_INCREMENT,
	`TYP_PRACY_DYPLOMOWEJ` varchar(15) NOT NULL,
	PRIMARY KEY (`TYP_PRACY_DYPLOMOWEJ_ID`)
);

CREATE TABLE `komisja_egzaminacyjna` (
	`PRACA_DYPLOMOWA_ID` INT NOT NULL,
	`PRACOWNIK_ID` INT NOT NULL
);

CREATE TABLE `prace_dyplomowe_studenta` (
	`NR_INDEKSU` varchar(15) DEFAULT 'NULL',
	`PRACA_DYPLOMOWA_ID` INT
);

CREATE TABLE `Promotorzy` (
	`PRACA_DYPLOMOWA_ID` INT NOT NULL,
	`PRACOWNIK_ID` INT NOT NULL
);

CREATE TABLE `kierunek_student` (
	`NR_INDEKSU` varchar(15) NOT NULL,
	`KIERUNEK_ID` varchar(10) NOT NULL
);

CREATE TABLE `grupa_student` (
	`NR_INDEKSU` varchar(15) NOT NULL,
	`GRUPA_ID` INT NOT NULL
);

CREATE TABLE `Stypendium` (
	`STYPENDIUM_ID` INT NOT NULL AUTO_INCREMENT,
	`WARTOSC_STYPENDIUM` DECIMAL(6,2) NOT NULL,
	`KIERUNEK_ID` varchar(10) NOT NULL,
	PRIMARY KEY (`STYPENDIUM_ID`)
);

CREATE TABLE `student_stypendium` (
	`NR_INDEKSU` varchar(15) DEFAULT 'NULL',
	`STYPENDIUM_ID` INT
);

ALTER TABLE `Adres` ADD CONSTRAINT `Adres_fk0` FOREIGN KEY (`MIASTO_ID`) REFERENCES `Miasto`(`MIASTO_ID`);

ALTER TABLE `Student` ADD CONSTRAINT `Student_fk0` FOREIGN KEY (`MIEJSCE_URODZENIA_ID`) REFERENCES `Miasto`(`MIASTO_ID`);

ALTER TABLE `Student` ADD CONSTRAINT `Student_fk1` FOREIGN KEY (`POMOC_MATERIALNA_ID`) REFERENCES `System_pomocy_studentom`(`POMOC_ID`);

ALTER TABLE `Kierunek` ADD CONSTRAINT `Kierunek_fk0` FOREIGN KEY (`WYDZIAL_ID`) REFERENCES `Wydzial`(`WYDZIAL_ID`);

ALTER TABLE `Zajecia` ADD CONSTRAINT `Zajecia_fk0` FOREIGN KEY (`PRACOWNIK_ID`) REFERENCES `Pracownik`(`PRACOWNIK_ID`);

ALTER TABLE `Zajecia` ADD CONSTRAINT `Zajecia_fk1` FOREIGN KEY (`PRZEDMIOT_ID`) REFERENCES `Przedmiot`(`PRZEDMIOT_ID`);

ALTER TABLE `Przedmiot` ADD CONSTRAINT `Przedmiot_fk0` FOREIGN KEY (`GRUPA_ID`) REFERENCES `Grupa`(`GRUPA_ID`);

ALTER TABLE `Przedmiot` ADD CONSTRAINT `Przedmiot_fk1` FOREIGN KEY (`SEMESTR_ID`) REFERENCES `Semestr`(`SEMESTR_ID`);

ALTER TABLE `Przedmiot` ADD CONSTRAINT `Przedmiot_fk2` FOREIGN KEY (`KIERUNEK_ID`) REFERENCES `Kierunek`(`KIERUNEK_ID`);

ALTER TABLE `Ocena` ADD CONSTRAINT `Ocena_fk0` FOREIGN KEY (`NR_INDEKSU`) REFERENCES `Student`(`NR_INDEKSU`);

ALTER TABLE `Ocena` ADD CONSTRAINT `Ocena_fk1` FOREIGN KEY (`PRZEDMIOT_ID`) REFERENCES `Przedmiot`(`PRZEDMIOT_ID`);

ALTER TABLE `Wydzial` ADD CONSTRAINT `Wydzial_fk0` FOREIGN KEY (`ADRES_ID`) REFERENCES `Adres`(`ADRES_ID`);

ALTER TABLE `Praca_dyplomowa` ADD CONSTRAINT `Praca_dyplomowa_fk0` FOREIGN KEY (`TYP_PRACY_DYPLOMOWEJ_ID`) REFERENCES `Typ_pracy_dyplomowej`(`TYP_PRACY_DYPLOMOWEJ_ID`);

ALTER TABLE `Praca_dyplomowa` ADD CONSTRAINT `Praca_dyplomowa_fk1` FOREIGN KEY (`RECENZENT_ID`) REFERENCES `Pracownik`(`PRACOWNIK_ID`);

ALTER TABLE `student_platnosci` ADD CONSTRAINT `student_platnosci_fk0` FOREIGN KEY (`NR_INDEKSU`) REFERENCES `Student`(`NR_INDEKSU`);

ALTER TABLE `student_platnosci` ADD CONSTRAINT `student_platnosci_fk1` FOREIGN KEY (`PLATNOSCI_ID`) REFERENCES `Platnosci`(`PLATNOSCI_ID`);

ALTER TABLE `System_pomocy_studentom` ADD CONSTRAINT `System_pomocy_studentom_fk0` FOREIGN KEY (`MIEJSCE_W_AKADEMIKU_ID`) REFERENCES `Miejsce_w_akademiku`(`MIEJSCE_W_AKADEMIKU_ID`);

ALTER TABLE `System_pomocy_studentom` ADD CONSTRAINT `System_pomocy_studentom_fk1` FOREIGN KEY (`STYPENDIUM_ID`) REFERENCES `Stypendium`(`STYPENDIUM_ID`);

ALTER TABLE `Miejsce_w_akademiku` ADD CONSTRAINT `Miejsce_w_akademiku_fk0` FOREIGN KEY (`AKADEMIK_ID`) REFERENCES `Akademik`(`AKADEMIK_ID`);

ALTER TABLE `Miejsce_w_akademiku` ADD CONSTRAINT `Miejsce_w_akademiku_fk1` FOREIGN KEY (`NUMER_POKOJU_ID`) REFERENCES `Numer_pokoju`(`NUMER_POKOJU_ID`);

ALTER TABLE `Akademik` ADD CONSTRAINT `Akademik_fk0` FOREIGN KEY (`ADRES_ID`) REFERENCES `Adres`(`ADRES_ID`);

ALTER TABLE `komisja_egzaminacyjna` ADD CONSTRAINT `komisja_egzaminacyjna_fk0` FOREIGN KEY (`PRACA_DYPLOMOWA_ID`) REFERENCES `Praca_dyplomowa`(`PRACA_DYPLOMOWA_ID`);

ALTER TABLE `komisja_egzaminacyjna` ADD CONSTRAINT `komisja_egzaminacyjna_fk1` FOREIGN KEY (`PRACOWNIK_ID`) REFERENCES `Pracownik`(`PRACOWNIK_ID`);

ALTER TABLE `prace_dyplomowe_studenta` ADD CONSTRAINT `prace_dyplomowe_studenta_fk0` FOREIGN KEY (`NR_INDEKSU`) REFERENCES `Student`(`NR_INDEKSU`);

ALTER TABLE `prace_dyplomowe_studenta` ADD CONSTRAINT `prace_dyplomowe_studenta_fk1` FOREIGN KEY (`PRACA_DYPLOMOWA_ID`) REFERENCES `Praca_dyplomowa`(`PRACA_DYPLOMOWA_ID`);

ALTER TABLE `Promotorzy` ADD CONSTRAINT `Promotorzy_fk0` FOREIGN KEY (`PRACA_DYPLOMOWA_ID`) REFERENCES `Praca_dyplomowa`(`PRACA_DYPLOMOWA_ID`);

ALTER TABLE `Promotorzy` ADD CONSTRAINT `Promotorzy_fk1` FOREIGN KEY (`PRACOWNIK_ID`) REFERENCES `Pracownik`(`PRACOWNIK_ID`);

ALTER TABLE `kierunek_student` ADD CONSTRAINT `kierunek_student_fk0` FOREIGN KEY (`NR_INDEKSU`) REFERENCES `Student`(`NR_INDEKSU`);

ALTER TABLE `kierunek_student` ADD CONSTRAINT `kierunek_student_fk1` FOREIGN KEY (`KIERUNEK_ID`) REFERENCES `Kierunek`(`KIERUNEK_ID`);

ALTER TABLE `grupa_student` ADD CONSTRAINT `grupa_student_fk0` FOREIGN KEY (`NR_INDEKSU`) REFERENCES `Student`(`NR_INDEKSU`);

ALTER TABLE `grupa_student` ADD CONSTRAINT `grupa_student_fk1` FOREIGN KEY (`GRUPA_ID`) REFERENCES `Grupa`(`GRUPA_ID`);

ALTER TABLE `Stypendium` ADD CONSTRAINT `Stypendium_fk0` FOREIGN KEY (`KIERUNEK_ID`) REFERENCES `Kierunek`(`KIERUNEK_ID`);

ALTER TABLE `student_stypendium` ADD CONSTRAINT `student_stypendium_fk0` FOREIGN KEY (`NR_INDEKSU`) REFERENCES `Student`(`NR_INDEKSU`);

ALTER TABLE `student_stypendium` ADD CONSTRAINT `student_stypendium_fk1` FOREIGN KEY (`STYPENDIUM_ID`) REFERENCES `Stypendium`(`STYPENDIUM_ID`);

