SELECT IMIE,NAZWISKO,MIASTO FROM Student AS S JOIN Miasto AS M ON S.MIEJSCE_URODZENIA_ID=M.MIASTO_ID WHERE MIEJSCE_URODZENIA_ID IN("GA","GDA","SPT") AND DATA_ZAKONCZENIA_STUDIOW IS NOT NULL ORDER BY NAZWISKO;

SELECT TYTUL_WPLATY,WYSOKOSC_OPLATY,DATA_WPLATY FROM Student AS S JOIN student_platnosci AS s_p ON S.NR_INDEKSU=s_p.NR_INDEKSU JOIN Platnosci AS P ON s_p.PLATNOSCI_ID=P.PLATNOSCI_ID WHERE S.NR_INDEKSU LIKE 74863 ORDER BY DATA_WPLATY;

SELECT CONCAT(IMIE,' ',NAZWISKO) AS 'Dane studenta', CASE 	WHEN ADRES_EMAIL LIKE '%wp.pl' THEN 'wp.pl' WHEN ADRES_EMAIL LIKE '%gmail.com' THEN 'google.com' WHEN ADRES_EMAIL LIKE '%o2.pl' THEN 'o2.pl' 
WHEN ADRES_EMAIL LIKE '%onet.pl' THEN 'onet.pl'ELSE 'brak adresu' END AS 'adres domeny internetowej poczty' FROM Student;

SELECT COUNT(s_p.PLATNOSCI_ID) AS "ILOSC WARUNKOW STUDENTA", SUM(WYSOKOSC_OPLATY) AS "WARTOSC ZAPLACONA PRZEZ STUDENTA ZA WSZYSTKIE WARUNKI" FROM Student AS S JOIN student_platnosci AS s_p ON S.NR_INDEKSU=s_p.NR_INDEKSU JOIN Platnosci AS P ON s_p.PLATNOSCI_ID=P.PLATNOSCI_ID WHERE TYTUL_WPLATY="warunek" AND NAZWISKO="Herman";

SELECT WARTOSC_STYPENDIUM,NAZWA_KIERUNKU from Student AS S JOIN student_stypendium AS s_s ON S.NR_INDEKSU=s_s.NR_INDEKSU JOIN Stypendium AS St ON s_s.STYPENDIUM_ID=St.STYPENDIUM_ID JOIN Kierunek AS K ON St.KIERUNEK_ID=K.KIERUNEK_ID WHERE NAZWISKO="Kowalski";

SELECT CONCAT(IMIE,' ',NAZWISKO) AS "Dane osoby", PRACA_DYPLOMOWA_TYTUL,TYP_PRACY_DYPLOMOWEJ,DATA_OBRONY FROM Student AS S JOIN prace_dyplomowe_studenta AS pds ON pds.NR_INDEKSU=S.NR_INDEKSU JOIN Praca_dyplomowa AS Pd ON Pd.PRACA_DYPLOMOWA_ID=pds.PRACA_DYPLOMOWA_ID JOIN Typ_pracy_dyplomowej AS Tpd ON Tpd.TYP_PRACY_DYPLOMOWEJ_ID=Pd.TYP_PRACY_DYPLOMOWEJ_ID ORDER BY DATA_OBRONY;

SELECT CONCAT(S.IMIE,' ',S.NAZWISKO) AS "Dane osoby", PRACA_DYPLOMOWA_TYTUL,OCENA_ZA_PRACE,OCENA_ZA_OBRONE,DATA_OBRONY, CONCAT(P.IMIE,' ',P.NAZWISKO) AS RECENZENT FROM Student AS S JOIN prace_dyplomowe_studenta AS pds ON pds.NR_INDEKSU=S.NR_INDEKSU JOIN Praca_dyplomowa AS Pd ON Pd.PRACA_DYPLOMOWA_ID=pds.PRACA_DYPLOMOWA_ID JOIN Typ_pracy_dyplomowej AS Tpd ON Tpd.TYP_PRACY_DYPLOMOWEJ_ID=Pd.TYP_PRACY_DYPLOMOWEJ_ID JOIN Pracownik AS P ON Pd.RECENZENT_ID=P.PRACOWNIK_ID WHERE TYP_PRACY_DYPLOMOWEJ="magisterska" ORDER BY OCENA_ZA_OBRONE+OCENA_ZA_PRACE DESC;

SELECT CONCAT(P.IMIE,' ',P.NAZWISKO) AS "Dane komisji egzaminacyjnej" FROM Praca_dyplomowa AS Pd JOIN komisja_egzaminacyjna AS ke ON Pd.PRACA_DYPLOMOWA_ID=ke.PRACA_DYPLOMOWA_ID JOIN Pracownik AS P ON P.PRACOWNIK_ID=ke.PRACOWNIK_ID JOIN prace_dyplomowe_studenta AS pds ON Pd.PRACA_DYPLOMOWA_ID=pds.PRACA_DYPLOMOWA_ID JOIN Student AS S ON pds.NR_INDEKSU=S.NR_INDEKSU WHERE S.NR_INDEKSU=74874;

SELECT CONCAT(P.IMIE,' ',P.NAZWISKO) AS "Dane promotorow",TYTUL_NAUKOWY  FROM Praca_dyplomowa AS Pd JOIN Promotorzy AS p ON Pd.PRACA_DYPLOMOWA_ID=p.PRACA_DYPLOMOWA_ID JOIN Pracownik AS P ON P.PRACOWNIK_ID=p.PRACOWNIK_ID JOIN prace_dyplomowe_studenta AS pds ON Pd.PRACA_DYPLOMOWA_ID=pds.PRACA_DYPLOMOWA_ID JOIN Student AS S ON pds.NR_INDEKSU=S.NR_INDEKSU JOIN Typ_pracy_dyplomowej AS Tpd ON Pd.TYP_PRACY_DYPLOMOWEJ_ID=Tpd.TYP_PRACY_DYPLOMOWEJ_ID WHERE S.NR_INDEKSU=74862 AND DATA_OBRONY='2013-06-20' ;

SELECT PRZEDMIOT_NAZWA,NAZWA_KIERUNKU, SEMESTR FROM Przedmiot AS P JOIN Zajecia AS Z ON Z.PRZEDMIOT_ID=P.PRZEDMIOT_ID JOIN Pracownik AS p ON Z.PRACOWNIK_ID=p.PRACOWNIK_ID JOIN Semestr AS S ON P.SEMESTR_ID=S.SEMESTR_ID JOIN Kierunek AS K ON K.KIERUNEK_ID=P.KIERUNEK_ID WHERE p.PRACOWNIK_ID=469;

SELECT PRACA_DYPLOMOWA_TYTUL FROM Praca_dyplomowa AS Pd JOIN Promotorzy AS P ON Pd.PRACA_DYPLOMOWA_ID=P.PRACA_DYPLOMOWA_ID JOIN Pracownik AS p ON P.PRACOWNIK_ID=p.PRACOWNIK_ID WHERE p.NAZWISKO="Kaczmarek";

SELECT CONCAT(IMIE,' ',NAZWISKO) AS Dane ,DATA_ROZPOCZECIA_STUDIOW,DATA_ZAKONCZENIA_STUDIOW,DATEDIFF(DATA_ZAKONCZENIA_STUDIOW,DATA_ROZPOCZECIA_STUDIOW) AS 'Liczba dni od rozpoczecia do konca studiow' FROM Student WHERE DATA_ZAKONCZENIA_STUDIOW IS NOT NULL;


SELECT POWER(2,3)*SQRT(9);

UPDATE Student SET NumerTelefonu = "348775486" WHERE NR_INDEKSU = "74873";
UPDATE Stypendium SET WARTOSC_STYPENDIUM = 2500 WHERE KIERUNEK_ID = "ARCH" OR KIERUNEK_ID = "MAT";
DELETE FROM Ocena WHERE NR_INDEKSU='74870' AND PRZEDMIOT_ID='131';

