CREATE VIEW SREDNIA_OCEN AS SELECT AVG(OCENA) AS 'Srednia ocen wszystkich obecnych studentow' FROM Ocena AS O JOIN Student AS S ON O.NR_INDEKSU=S.NR_INDEKSU WHERE S.DATA_ZAKONCZENIA_STUDIOW IS NULL;

SELECT WARTOSC_STYPENDIUM,NAZWA_KIERUNKU from Student AS S JOIN student_stypendium AS s_s ON S.NR_INDEKSU=s_s.NR_INDEKSU JOIN Stypendium AS St ON s_s.STYPENDIUM_ID=St.STYPENDIUM_ID JOIN Kierunek AS K ON St.KIERUNEK_ID=K.KIERUNEK_ID WHERE St.KIERUNEK_ID NOT LIKE "INF";

SELECT IMIE,NAZWISKO,MIASTO FROM Student AS S JOIN Miasto AS M ON S.MIEJSCE_URODZENIA_ID=M.MIASTO_ID WHERE MIEJSCE_URODZENIA_ID NOT IN("GA","GDA","SPT") AND DATA_ZAKONCZENIA_STUDIOW IS NULL ORDER BY NAZWISKO;

SELECT S1.IMIE,S1.NAZWISKO,S1.ADRES_EMAIL FROM Student AS S1 LEFT OUTER JOIN Student AS S2 ON S2.NR_INDEKSU = S1.NR_INDEKSU WHERE S2.POMOC_MATERIALNA_ID='111';


